name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-maven@v2  # Agregar paso para instalar Maven

    - name: Install dependencies
      run: |
        mvn clean install  # Usar mvn para instalar dependencias

    - name: Run tests
      run: |
        mvn test  # Usar mvn para ejecutar las pruebas

    - name: SonarQube Analysis
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectKey: 'TestingSQ'
        projectName: 'GarciaJonathan01/sonarQubeTesting'
        sonar.host.url: 'http://localhost:9000'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

